### ISSUE TITLE
Version checks between Plugins the Core-System

### ISSUE THREAD

**Issue by jschaefer-io** [progwerkzeugehtw-1-plugin/Core-System#5]
If we want to update the PluginInterface in the future, there will be some compativility issues with the existing Plugins. Therefore i suggest adding a `version`-parameter to the PluginLoader and to the Plugin Interface, this will ensure the compatibility.

```java
String version = "1.10";
PluginLoader  loader = new PluginLoader(pluginFolder, version);
```

```java
public interface PluginInterface {
        // ...
        String getVersion();
}
```

**Comment by NiklasSchuetz** [comment]
mach ich nachher
